name: "Dependency Review"

on:
  pull_request:
    branches: ["develop"]

permissions:
  contents: write
  security-events: write
  actions: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          comment-summary-in-pr: always
          config-file: .github/dependency-review-config.yml
